version: '3.8'

services:
  mariadb:
      image: mariadb:latest
      environment:
          MARIADB_ROOT_PASSWORD: root_password
          MARIADB_DATABASE: your_database
          MARIADB_USER: your_user
          MARIADB_PASSWORD: your_password
      ports:
          - "3306:3306"